apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-device-plugin
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - chart: nvidia-device-plugin
      repoURL: https://nvidia.github.io/k8s-device-plugin
      targetRevision: 0.18.1
      helm:
        releaseName: nvidia-device-plugin
        valueFiles:
          - $repo/devops/argocd/nvidia/values.yaml
    - repoURL: 'https://github.com/hnatekmarorg/devops-cluster.git'
      targetRevision: main
      ref: repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nvidia-device-plugin
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - CreateNamespace=false
