apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: truenas-secret
    namespace: hpe-storage
    annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:J4AiAEvXzbtyDIRXmwA=,iv:k7ZeVZ0lz+n86/Zhz6p7uXJwuNDdfJYoHB6I0eHyUX8=,tag:Qy5hJ6EzAgTYslwnPaL+1g==,type:str]
          stringData:
            serviceName: ENC[AES256_GCM,data:DsDnon+PXkRgFWDQpyNZ,iv:KXhUq4XBhnqjjdkW8+yiM3Gmte6Y8gb5sOj5YgOCWCk=,tag:dO7tlBvPBCQNfgXuYfRfow==,type:str]
            servicePort: ENC[AES256_GCM,data:moWgSQ==,iv:pJVwOMzAHBpANC5yTA0K8mpAwOsiK1rmuxIqazSGO+E=,tag:F8iNK808rfIix0cX9xxuYg==,type:str]
            username: ENC[AES256_GCM,data:MbSEC434ng==,iv:UDvc+CYa4I1FiiD5f4Ial2F0UssVv83NMEhlnGbJWlw=,tag:L69HqhVf8A3En1o733oSSw==,type:str]
            password: ENC[AES256_GCM,data:vmyoSqgT03u0XeCgK8GfMydiBWPHzoHNCmPldQHEAZ5TjfJ5txGG9QO/FjkeFlEviUlBeApQy3S3bxBL3r1FRsD/,iv:NI3aZhKbUakv5dM3C5ralsMRSobt4tRSO+UuI7lbqm0=,tag:ngBLWMNEx09gjUWCp0Jpug==,type:str]
            backend: ENC[AES256_GCM,data:V+hcOKRj0FBgnYZuVR6HCqMQs9Y=,iv:MWDVpQ41SOA23g2Gu0j2JRqH8nIPSyJFV3fsSNst2AI=,tag:/ZMUUYPKZPl/xOAsoK4uvA==,type:str]
sops:
    age:
        - recipient: age1t9wspfgy0nxrc9d3frmp85g4d5ug6ksf66pv68ycptv0fwsxq9fqxuhma9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWCtlYWVTY2F2ZnQySmd0
            YzhTSjlXbjZyYnM2TlJORGV6SUdzaFFxSFFBClVIN3Rwcy9hL201NTM2SnFuTGdN
            WGZCWUcya0dKSy9UTVhsUTJXdHd1MTgKLS0tIEtONkRJVlFnRCtRTjZWY0N6MDly
            U2xDMzA3VnlJbzFEL1dKMkJjN2UwdGsKV11U0wQUghbKttDURzYgIFQvKubwfTKD
            xyXKA/c0bdprJFAP3Sojz5dkXeVAMLiqX0GAurHQ2/rNzxFSrHylpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T16:23:02Z"
    mac: ENC[AES256_GCM,data:bKTWx4OEIDiIBgGpUEB6nReg0xdAFhu3wYCwrrkPrsmMGLfeiHzmKoqkTudt+E2+Ir+3pukCMZW8u9o1UiG4O/GTafeDSL6Z0qY/0D5+jrNwPZlgL2/h+7goCrtjNBfuGteQrrdLtnCCPsOs3Fcok03Ft0sZ9TfqXkNmr0bMMwM=,iv:MXN3lP0wEgN/ZXWyw+UIo3X8PNsq8F/hkobd6qHAdnQ=,tag:ECJIki1Ccs7nhcZVjPD95Q==,type:str]
    encrypted_suffix: Templates
    version: 3.11.0
