apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thingsboard
  namespace: thingsboard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - thingsboard.hnatekmar.dev
      secretName: thingsboard-tls
  rules:
    - host: thingsboard.hnatekmar.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thingsboard
                port:
                  number: 8080