apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chromadb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://amikos-tech.github.io/chromadb-chart/
      chart: chromadb
      targetRevision: 0.1.24
      helm:
        valueFiles:
          - $repo/devops/argocd/chromadb/values.yaml
    - repoURL: 'https://github.com/hnatekmarorg/devops-cluster.git'
      targetRevision: main
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: chromadb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
