
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - name: chart
      repoURL: https://github.com/hnatekmarorg/scale
      path: helm-chart/
      targetRevision: main
      helm:
        valueFiles:
          - $repo/devops/argocd/scale/values.yaml
    - repoURL: 'https://github.com/hnatekmarorg/devops-cluster.git'
      targetRevision: main
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: scale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
