{{ if .Values.onprem }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-async
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - chart: nfs-subdir-external-provisioner
      repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      targetRevision: 4.0.18
      helm:
        releaseName: nfs-subdir-external-provisioner
        valuesObject:
          volume-name: nfs-async
          nfs:
            server: 192.168.88.25
            mountOptions:
              - hard
              - intr
              - async
              - proto=tcp
              - noacl
              - nfsvers=4.2
              - noatime
            path: /mnt/data/k8s
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
{{end}}