
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-cpp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  ignoreDifferences:
    - kind: "*"
      group: "*"
      namespace: inference
      jsonPointers:
        - /spec/replicas
  sources:
    - name: chart
      repoURL: https://github.com/hnatekmarorg/devops-cluster.git
      path: charts/llama-cpp
      targetRevision: main
      helm:
        valueFiles:
          - $repo/devops/argocd/llama/values.yaml
    - repoURL: 'https://github.com/hnatekmarorg/devops-cluster.git'
      targetRevision: main
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
